global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these extra labels to all time-series collected by this Prometheus instance.
  labels:
    monitor: 'panamax-monitor'


# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  static_configs:
    - targets: ['localhost:9393']
      labels:
        group: 'production'